---
doc_auth:
  general_error: A random error with no friendly message
  document_type_could_not_be_determined: The document type could not be determined
  barcode_could_not_be_read: The 2D barcode could not be read
  pattern_not_found: A visible pattern was not found
  evidence_tampered: Evidence suggests the image has been tampered with or digitally manipulated.
  photo_print_technique_not_detected: The photo printing technique was not detected
  document_has_expired: The document has expired
  birth_date_not_valid: The birth date is not valid
  expiration_date_is_not_valid: The expiration date is not valid
  substrate_print_technique_not_detected: The substrate printing technique was not detected
  color_response_incorrect: The color response is incorrect
  issue_date_is_not_valid: The issue date is not valid
  full_names_do_not_match: The full names do not match
  document_number_check_digit_is_incorrect: The document number check digit is incorrect
  photo_lacks_expected_appearance: The photo lacks the expected appearance
  birth_dates_do_not_match: The birth dates do not match
  control_numbers_do_not_match: The control numbers do not match
  check_digit_is_incorrect: The composite check digit is incorrect
  sexes_do_not_match: The sexes do not match
  barcode_formatted_incorrectly: The 2D barcode is formatted incorrectly
  document_image_load_failure: Document image load failure
  document_not_found: Document Not Found
  color_pixel_depth: Color pixel depth must be 24-bit
  duplicate_document_side: Duplicate Document Side
  document_complete_or_error: Document complete or in error state
  internal_server_error: Internal Server Error