engines:
  brakeman:
    enabled: false
  bundler-audit:
    enabled: false
  coffeelint:
    enabled: true
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby
        # mass_threshold: 30
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
  scss-lint:
    enabled: false

ratings:
  paths:
  - app/**
  - lib/**
  - '**.rb'
  - '**.go'

exclude_paths:
- code/upaya/spec/**/*
- 'code/upaya/vendor/assets/stylesheets/uswds.css'
- 'code/upaya/db/migrate/20160405212342_initial_schema.rb'
