exclude:
    - 'app/views/shared/_flashes.html.slim'
linters:
  LineLength:
    max: 100
    exclude:
      - 'app/views/pages/help.html.slim'
      - 'app/views/pages/privacy_policy.html.slim'
  RuboCop:
    enabled: true
