test:
  'http://idmanagement.gov/ns/assurance/loa/2': 'https://loa2.example.com'
  'http://idmanagement.gov/ns/assurance/loa/3': 'https://loa3.example.com'
  'http://idmanagement.gov/ns/assurance/loa/4': 'https://loa4.example.com'

development:
  'http://idmanagement.gov/ns/assurance/loa/2': 'https://loa2.example.com'
  'http://idmanagement.gov/ns/assurance/loa/3': 'https://loa3.example.com'
  'http://idmanagement.gov/ns/assurance/loa/4': 'https://loa4.example.com'

production:
  'http://idmanagement.gov/ns/assurance/loa/2': 'https://loa2.example.com'
  'http://idmanagement.gov/ns/assurance/loa/3': 'https://loa3.example.com'
  'http://idmanagement.gov/ns/assurance/loa/4': 'https://loa4.example.com'
