test:
  valid_hosts:
    'http://localhost:3000':
      acs_url: 'http://localhost:3000/test/saml/decode_assertion'
      assertion_consumer_logout_service_url: 'http://localhost:3000/test/saml/decode_slo_request'
      sp_initiated_login_url: 'http://localhost:3000/test/saml'
      cert: 'saml_test_sp'
      agency: 'test_agency'
      friendly_name: 'test_friendly_name'

    'https://rp1.serviceprovider.com/auth/saml/metadata':
      acs_url: 'http://example.com/test/saml/decode_assertion'
      assertion_consumer_logout_service_url: 'http://example.com/test/saml/decode_slo_request'
      sp_initiated_login_url: 'https://example.com/auth/saml/login'
      cert: 'saml_test_sp'

    'https://rp2.serviceprovider.com/auth/saml/metadata':
      acs_url: 'http://example.com/test/saml/decode_assertion'
      assertion_consumer_logout_service_url: 'http://example.com/test/saml/decode_slo_request'
      cert: 'saml_test_sp'

    'http://test.host':
      acs_url: 'http://test.host/test/saml/decode_assertion'
      metadata_url: 'http://test.host/test/saml/metadata'
      sp_initiated_login_url: 'http://test.host/test/saml'

development:
  valid_hosts:
    'https://rp1.serviceprovider.com/auth/saml/metadata':
      metadata_url: 'http://localhost:3000/test/saml/metadata'
      acs_url: 'http://localhost:3000/test/saml/decode_assertion'
      assertion_consumer_logout_service_url: 'http://localhost:3000/test/saml/decode_slo_request'
      sp_initiated_login_url: 'http://localhost:3000/test/saml'
      cert: 'saml_test_sp'
      fingerprint: '08:79:F5:B1:B8:CC:EC:8F:5C:2A:58:03:30:14:C9:E6:F1:67:78:F1:97:E8:3A:88:EB:8E:70:92:25:D2:2F:32'
    'urn:gov:gsa:SAML:2.0.profiles:sp:sso:localhost':
      metadata_url: 'http://localhost:4567/saml/metadata'
      acs_url: 'http://localhost:4567/consume'
      sp_initiated_login_url: 'http://localhost:4567/test/saml'
      assertion_consumer_logout_service_url: 'http://localhost:4567/slo_logout'
      cert: 'demo_sp'
    'urn:gov:gsa:SAML:2.0.profiles:sp:sso:localhost-rails':
      metadata_url: 'http://localhost:3003/saml/metadata'
      acs_url: 'http://localhost:3003/auth/saml/callback'
      assertion_consumer_logout_service_url: 'http://localhost:3003/auth/saml/logout'
      sp_initiated_login_url: 'http://localhost:3003/login'
      cert: 'demo_sp'
      agency: '18F'
      friendly_name: '18F Test Service Provider'
    'https://dashboard.login.gov':
      metadata_url: 'http://localhost:3001/users/auth/saml/metadata'
      acs_url: 'http://localhost:3001/users/auth/saml/callback'
      assertion_consumer_logout_service_url: 'http://localhost:3001/users/auth/saml/logout'
      sp_initiated_login_url: 'http://localhost:3001/users/auth/saml'
      cert: 'identity_dashboard_cert'

production:
  valid_hosts:
    'https://upaya-dev.18f.gov':
      metadata_url: 'https://upaya-dev.18f.gov/api/saml/metadata'
      acs_url: 'https://upaya-dev.18f.gov/test/saml/decode_assertion'
      assertion_consumer_logout_service_url: 'https://upaya-dev.18f.gov/test/saml/decode_logoutresponse'
      sp_initiated_login_url: 'https://upaya-dev.18f.gov/test/saml'
      cert: 'saml_test_sp'
    'urn:gov:gsa:SAML:2.0.profiles:sp:sso:localhost':
      metadata_url: 'http://localhost:4567/saml/metadata'
      acs_url: 'http://localhost:4567/consume'
      sp_initiated_login_url: 'http://localhost:4567/test/saml'
      cert: 'demo_sp'
    'urn:gov:gsa:SAML:2.0.profiles:sp:sso:dev':
      metadata_url: 'https://identity-rp-dev.apps.cloud.gov/saml/metadata'
      acs_url: 'https://identity-rp-dev.apps.cloud.gov/consume'
      assertion_consumer_logout_service_url: 'https://identity-rp-dev.apps.cloud.gov/slo_logout'
      sp_initiated_login_url: 'https://identity-rp-dev.apps.cloud.gov/test/saml'
      cert: 'demo_sp'
    'urn:gov:gsa:SAML:2.0.profiles:sp:sso:demo':
      metadata_url: 'https://identity-rp-demo.apps.cloud.gov/saml/metadata'
      acs_url: 'https://identity-rp-demo.apps.cloud.gov/consume'
      assertion_consumer_logout_service_url: 'https://identity-rp-demo.apps.cloud.gov/slo_logout'
      sp_initiated_login_url: 'https://identity-rp-demo.apps.cloud.gov/test/saml'
      cert: 'demo_sp'
    'urn:gov:gsa:SAML:2.0.profiles:sp:sso:rails-dev':
      metadata_url: 'https://identity-sp-rails-dev.apps.cloud.gov/saml/metadata'
      acs_url: 'https://identity-sp-rails-dev.apps.cloud.gov/auth/saml/callback'
      assertion_consumer_logout_service_url: 'https://identity-sp-rails-dev.apps.cloud.gov/auth/saml/logout'
      sp_initiated_login_url: 'https://identity-sp-rails-dev.apps.cloud.gov/login'
      cert: 'demo_sp'
    'urn:gov:gsa:SAML:2.0.profiles:sp:sso:rails-demo':
      metadata_url: 'https://identity-sp-rails-demo.apps.cloud.gov/saml/metadata'
      acs_url: 'https://identity-sp-rails-demo.apps.cloud.gov/auth/saml/callback'
      assertion_consumer_logout_service_url: 'https://identity-sp-rails-demo.apps.cloud.gov/auth/saml/logout'
      sp_initiated_login_url: 'https://identity-sp-rails-demo.apps.cloud.gov/login'
      cert: 'demo_sp'
    'urn:gov:gsa:SAML:2.0.profiles:sp:sso:dashboard-dev':
      metadata_url: 'https://identity-dashboard-dev.apps.cloud.gov/users/auth/saml/metadata'
      acs_url: 'https://identity-dashboard-dev.apps.cloud.gov/users/auth/saml/callback'
      assertion_consumer_logout_service_url: 'https://identity-dashboard-dev.apps.cloud.gov/users/auth/saml/logout'
      sp_initiated_login_url: 'https://identity-dashboard-dev.apps.cloud.gov/users/auth/saml'
      cert: 'identity_dashboard_cert'
    'urn:gov:gsa:SAML:2.0.profiles:sp:sso:dashboard-demo':
      metadata_url: 'https://identity-dashboard-demo.apps.cloud.gov/users/auth/saml/metadata'
      acs_url: 'https://identity-dashboard-demo.apps.cloud.gov/users/auth/saml/callback'
      assertion_consumer_logout_service_url: 'https://identity-dashboard-demo.apps.cloud.gov/users/auth/saml/logout'
      sp_initiated_login_url: 'https://identity-dashboard-demo.apps.cloud.gov/users/auth/saml'
      cert: 'identity_dashboard_cert'

superb.legit.domain.gov:
  valid_hosts:
    'urn:govheroku:serviceprovider':
      acs_url: 'https://vets.gov/users/auth/saml/callback'
      assertion_consumer_logout_service_url: 'https://vets.gov/api/saml/logout'
      cert: 'saml_test_sp'
      agency: 'test_agency'
