apiVersion: v1
kind: ConfigMap
metadata:
  name: idp
  namespace: identity-platform
data:
  application.yml: |
    RACK_TIMEOUT_SERVICE_TIMEOUT: '15'
    aamva_cert_enabled: 'true'
    aamva_sp_banlist_issuers: '[]'
    account_reset_token_valid_for_days: '1'
    account_reset_wait_period_days: '1'
    acuant_assure_id_password: ''
    acuant_assure_id_subscription_id: ''
    acuant_assure_id_username: ''
    acuant_attempt_window_in_minutes: '1440'
    acuant_facial_match_license_key: ''
    acuant_sdk_initialization_creds: 'aWRzY2FuZ293ZWJAYWN1YW50Y29ycC5jb206NVZLcm81Z0JEc1hrdFh2NA=='
    acuant_sdk_initialization_endpoint: 'https://services.assureid.net'
    acuant_timeout: '45'
    add_email_link_valid_for_hours: '24'
    allow_doc_auth_test_credentials:
    asset_host:
    async_job_refresh_max_wait_seconds: '15'
    available_locales: en es fr
    aws_http_timeout: '5'
    aws_logo_bucket:
    cac_proofing_enabled:
    database_statement_timeout: '2500'
    disallow_ial2_recovery:
    doc_capture_request_valid_for_minutes: '15'
    doc_auth_extend_timeout_by_minutes: '40'
    email_from: no-reply@login.gov
    enable_load_testing_mode: 'false'
    event_disavowal_expiration_hours: '240'
    google_analytics_key:
    google_analytics_timeout: '5'
    ial2_recovery_request_valid_for_minutes: '15'
    identity_pki_disabled: 'true'
    identity_pki_local_dev: 'false'
    idv_attempt_window_in_hours: '24'
    idv_max_attempts: '3'
    idv_send_link_attempt_window_in_minutes: '10'
    idv_send_link_max_attempts: '5'
    in_person_proofing_enabled:
    job_run_healthchecks_enabled: 'true'
    lexisnexis_account_id: test_account
    lexisnexis_base_url: https://www.example.com
    lexisnexis_instant_verify_workflow: customers.gsa.instant.verify.workflow
    lexisnexis_password: test_password
    lexisnexis_phone_finder_workflow: customers.gsa.phonefinder.workflow
    lexisnexis_request_mode: testing
    lexisnexis_username: test_username
    logins_per_email_and_ip_bantime: '60'
    logins_per_email_and_ip_period: '60'
    logins_per_ip_period: '60'
    logo_upload_enabled: 'false'
    mailer_domain_name: http://localhost:3000
    max_auth_apps_per_account: '2'
    max_emails_per_account: '12'
    max_mail_events_window_in_days: '30'
    max_piv_cac_per_account: '2'
    min_password_score: '3'
    mx_timeout: '3'
    otp_valid_for: '10'
    password_max_attempts: '3'
    personal_key_retired: 'true'
    pinpoint_sms_application_id:
    pinpoint_sms_credential_role_arn:
    pinpoint_sms_longcode_pool:
    pinpoint_sms_region:
    pinpoint_sms_shortcode:
    pinpoint_voice_credential_role_arn:
    pinpoint_voice_longcode_pool:
    pinpoint_voice_region:
    proofer_mock_fallback: 'true'
    proofer_vendors:
    push_notifications_enabled:
    reauthn_window: '120'
    recaptcha_enabled_percent: '0'
    recaptcha_secret_key: key2
    recaptcha_site_key: key1
    recovery_code_length: '4'
    reg_confirmed_email_window_in_minutes: '60'
    remember_device_expiration_hours_aal_1: '720'
    remember_device_expiration_hours_aal_2: '12'
    report_timeout:
    requests_per_ip_track_only_mode: 'false'
    saml_secret_rotation_enabled:
    service_provider_request_ttl_hours: '24'
    session_check_delay: '30'
    session_check_frequency: '30'
    session_timeout_in_minutes: '15'
    session_timeout_warning_seconds: '150'
    sp_handoff_bounce_max_seconds: '2'
    show_user_attribute_deprecation_warnings: 'false'
    twilio_auth_token: token1
    twilio_http_basic_auth_password:
    twilio_http_basic_auth_username:
    twilio_messaging_service_sid:
    twilio_numbers:
    twilio_record_voice: 'false'
    twilio_sid:
    twilio_timeout: '5'
    unauthorized_scope_enabled: 'false'
    usps_download_sftp_timeout: '5'
    usps_upload_enabled: 'false'
    usps_upload_sftp_timeout: '5'
    valid_authn_contexts: '["http://idmanagement.gov/ns/assurance/loa/1", "http://idmanagement.gov/ns/assurance/loa/3", "http://idmanagement.gov/ns/assurance/ial/1", "http://idmanagement.gov/ns/assurance/ial/2", "http://idmanagement.gov/ns/assurance/ial/0"]'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: idp-db-dev
  namespace: identity-platform
data:
  database.yml: |
    development:
      adapter: postgresql
      encoding: utf8
      database: upaya_dev
      port: 5432
      username: postgres
      host: idp-postgresql
      pool: 5
      timeout: 30
      reconnect: true
      connect_timeout: 2
      keepalives_idle: 10
      keepalives_interval: 10
      keepalives_count: 2
      checkout_timeout: 5
      reaping_frequency: 10
      variables:
        statement_timeout: 2500
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: idp-db
  namespace: identity-platform
data:
  database.yml: |
    production:
      adapter: postgresql
      encoding: utf8
      database: upaya_dev
      port: 5432
      username: postgres
      host: idp-postgresql
      pool: 5
      timeout: 30
      reconnect: true
      connect_timeout: 2
      keepalives_idle: 10
      keepalives_interval: 10
      keepalives_count: 2
      checkout_timeout: 5
      reaping_frequency: 10
      variables:
        statement_timeout: 2500
      sslmode: 'verify-full'
      # todo (mxplusb): use aws-rds secret or something
      sslrootcert: '/usr/local/share/aws/rds-combined-ca-bundle.pem'
